# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(choices=[('CN', 'Chinese'), ('EN', 'English')], default='EN', max_length=2)),
                ('quoter', models.CharField(choices=[('Tushare', 'Tushare'), ('Local', 'Local')], default='Local', max_length=10)),
            ],
        ),
    ]
