# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 10:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='quoter',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='quoter_map',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
