# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:42
from __future__ import unicode_literals

import core.types
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
        ('portfolios', '0004_auto_20160921_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField(default=0)),
                ('cost', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('gain', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('dividend', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('value', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Security')),
            ],
        ),
    ]
