# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='date',
            field=models.DateField(default=datetime.date(2016, 1, 1)),
            preserve_default=False,
        ),
    ]
