# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 15:34
from __future__ import unicode_literals

import core.types
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_holding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='cost',
            field=core.types.PositiveDecimalField(decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='holding',
            name='dividend',
            field=core.types.PositiveDecimalField(decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='holding',
            name='gain',
            field=core.types.PositiveDecimalField(decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='holding',
            name='value',
            field=core.types.PositiveDecimalField(decimal_places=28, default=0, max_digits=38),
        ),
    ]
