# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20161108_1357'),
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioperformance',
            options={},
        ),
        migrations.AlterField(
            model_name='benchmarkperformance',
            name='benchmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='benchmarks.Benchmark'),
        ),
        migrations.AlterField(
            model_name='portfolioperformance',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='portfolios.Portfolio'),
        ),
        migrations.AlterField(
            model_name='securityperformance',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='securities.Security'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioperformance',
            unique_together=set([('portfolio', 'date')]),
        ),
    ]
