# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(default='', max_length=10)),
                ('quoter', models.CharField(blank=True, max_length=20)),
                ('isindex', models.BooleanField(default=False)),
            ],
        ),
    ]
