# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='currency',
            field=models.CharField(choices=[('CNY', 'Chinese Yuan'), ('USD', 'US Dollar'), ('HKD', 'HK Dollar')], default='CNY', max_length=3),
        ),
    ]
