# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_auto_20160927_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('total_shares', models.IntegerField()),
                ('outstanding_shares', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'valid_date',
            },
        ),
        migrations.RemoveField(
            model_name='security',
            name='name',
        ),
        migrations.AddField(
            model_name='securityinfo',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='securities.Security'),
        ),
        migrations.AlterUniqueTogether(
            name='securityinfo',
            unique_together=set([('security', 'valid_date')]),
        ),
    ]
