# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_auto_20161026_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityinfo',
            name='list_date',
            field=models.DateField(null=True, verbose_name='Date got Listed'),
        ),
        migrations.AlterField(
            model_name='securityinfo',
            name='industry',
            field=models.CharField(max_length=50, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='securityinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='securityinfo',
            name='outstanding_shares',
            field=models.IntegerField(null=True, verbose_name='Outstanding Shares'),
        ),
        migrations.AlterField(
            model_name='securityinfo',
            name='total_shares',
            field=models.IntegerField(null=True, verbose_name='Total Shares'),
        ),
        migrations.AlterField(
            model_name='securityinfo',
            name='valid_date',
            field=models.DateField(verbose_name='Valid Date'),
        ),
    ]
