# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0006_auto_20161027_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveField(
            model_name='securityinfo',
            name='list_date',
        ),
        migrations.AddField(
            model_name='security',
            name='list_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='quoter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
