# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0007_auto_20161030_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityinfo',
            name='outstanding_shares',
        ),
        migrations.RemoveField(
            model_name='securityinfo',
            name='total_shares',
        ),
    ]
