# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0008_auto_20161031_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='list_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
