# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0009_auto_20161031_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='quoter',
            new_name='exchange',
        ),
    ]
