# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0011_auto_20161110_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityinfo',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry'),
        ),
    ]
