# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0012_auto_20161110_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='exchange',
            field=models.CharField(blank=True, choices=[('SSE', 'Shanghai Stock Exchange'), ('SZSE', 'Shenzhen Stock Exchange'), ('NYSE', 'Newyork Stock Exchange'), ('NASDAQ', 'Nasdaq Stock Market'), ('HKEX', 'Hongkong Stock Exchange')], max_length=20, null=True),
        ),
    ]
