# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0013_auto_20161114_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['exchange', 'symbol']},
        ),
    ]
