# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 10:14
from __future__ import unicode_literals

import core.types
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3, unique_for_date=models.DateField())),
                ('rate', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
            ],
        ),
    ]
