# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'get_latest_by': 'date'},
        ),
    ]
