# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('shares', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=15)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Security')),
            ],
        ),
    ]
