# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:55
from __future__ import unicode_literals

import core.types
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securities', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('price', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('shares', models.PositiveIntegerField()),
                ('fee', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividendTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('price', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('shares', models.PositiveIntegerField()),
                ('fee', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplitTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('ratio', core.types.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
