# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySellTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('shares', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=4, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividentTrasaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SplitTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='security',
        ),
        migrations.AddField(
            model_name='security',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='splittransaction',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Security'),
        ),
        migrations.AddField(
            model_name='dividenttrasaction',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Security'),
        ),
        migrations.AddField(
            model_name='buyselltransaction',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Security'),
        ),
    ]
