# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction2',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.Portfolio'),
        ),
    ]
