# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('transactions', '0002_auto_20160721_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('shares', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=4, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='BuySellTransaction',
            new_name='BuyTransaction',
        ),
    ]
