# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-22 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160721_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DividentTrasaction',
            new_name='DividendTrasaction',
        ),
    ]
