# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0009_auto_20161031_1050'),
        ('transactions', '0004_auto_20161103_0931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction2',
            unique_together=set([('security', 'datetime', 'type')]),
        ),
    ]
