# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-23 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160722_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buytransaction',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='dividendtrasaction',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='selltransaction',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='splittransaction',
            old_name='date',
            new_name='datetime',
        ),
    ]
