# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('transactions', '0005_auto_20160723_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', transactions.models.PositiveDecimalField(decimal_places=28, max_digits=38)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dividendtrasaction',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='dividendtrasaction',
            name='security',
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='fee',
            field=transactions.models.PositiveDecimalField(decimal_places=28, max_digits=38),
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='price',
            field=transactions.models.PositiveDecimalField(decimal_places=28, max_digits=38),
        ),
        migrations.AlterField(
            model_name='buytransaction',
            name='shares',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='fee',
            field=transactions.models.PositiveDecimalField(decimal_places=28, max_digits=38),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='price',
            field=transactions.models.PositiveDecimalField(decimal_places=28, max_digits=38),
        ),
        migrations.AlterField(
            model_name='selltransaction',
            name='shares',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='splittransaction',
            name='ratio',
            field=transactions.models.PositiveDecimalField(decimal_places=28, max_digits=38),
        ),
        migrations.DeleteModel(
            name='DividendTrasaction',
        ),
    ]
