# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20161103_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction2',
            new_name='Transaction',
        ),
    ]
