# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 21:28
from __future__ import unicode_literals

import core.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20161103_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dividend',
            field=core.types.PositiveDecimalField(blank=True, decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=core.types.PositiveDecimalField(blank=True, decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=core.types.PositiveDecimalField(blank=True, decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ratio',
            field=core.types.PositiveDecimalField(blank=True, decimal_places=28, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
