# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20161104_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
