# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20161001_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'get_latest_by': 'date'},
        ),
    ]
